"""Initial schema

Revision ID: 16a13af27e11
Revises: 
Create Date: 2026-07-07 23:10:58.851476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16a13af27e11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('blocked_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_sources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('articles', 'category',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('articles_url_key'), 'articles', type_='unique')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'embedding')
    op.drop_column('articles', 'created_at')
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, ((((COALESCE(title, ''::text) || ' '::text) || COALESCE(summary, ''::text)) || ' '::text) || COALESCE(content, ''::text)))", persisted=True), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('articles_url_key'), 'articles', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('articles', 'category',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
